"""Shipping the WAL and reclaiming the disk, measured under a failing sink.

    python run_shipping.py

`run_wal.py` measured what a durable local append costs and what it recovers.
It ends by saying the WAL "does NOT replace shipping" and "bounds the loss to
what has not yet shipped". Both of those were promises about code that did not
exist: `DurableAuditLog.drain()` moved records between two Python lists, and
nothing ever deleted anything, so the log grew forever and "shipped" meant
nothing a crash would respect.

This runs the real thing over a sink that goes down, comes back, and
permanently rejects one record, and reports what is on disk at every step.

Writes docs/SHIPPING.md.
"""
from __future__ import annotations

import shutil
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from gateway.shipping import (MemorySink, SegmentedWal, Shipper, Watermark)

TMP = ROOT / "data" / "shipping"
PER_CYCLE = 400
CYCLES = 12
SEGMENT_BYTES = 8 * 1024


def _record(i):
    return {"decision_id": "d{:06d}".format(i),
            "decision": "approve" if i % 9 else "decline",
            "score": round(0.031 + (i % 7) / 1000, 4),
            "amount_minor": 1000 + (i * 37) % 500_000,
            "reason": "velocity" if i % 5 == 0 else "score",
            "received_at": "2026-08-24T19:00:00Z"}


def _disk(wal) -> int:
    return sum(s.stat().st_size for s in wal.segments())


def main() -> int:
    if TMP.exists():
        shutil.rmtree(TMP)

    wal = SegmentedWal(TMP / "wal", segment_bytes=SEGMENT_BYTES)
    sink = MemorySink()
    shipper = Shipper(wal, Watermark(TMP / "watermark.json"), sink)

    # One record is malformed in a way the sink will never accept. Without a
    # poison path this single record blocks the watermark forever and the disk
    # fills up.
    poison_id = "d002000"
    sink.reject_ids = {poison_id}

    # The sink is down for cycles 4-6 inclusive.
    down = {4, 5, 6}

    rows = []
    written = 0
    peak_disk = 0
    for cycle in range(1, CYCLES + 1):
        for _ in range(PER_CYCLE):
            wal.append(_record(written))
            written += 1
        sink.up = cycle not in down
        before = _disk(wal)
        out = shipper.run()
        after = _disk(wal)
        peak_disk = max(peak_disk, before)
        rows.append({
            "cycle": cycle, "sink": "up" if sink.up else "DOWN",
            "written": written, "shipped": out["shipped"],
            "unshipped": out["unshipped_remaining"],
            "segments": len(wal.segments()),
            "deleted": out["segments_deleted"],
            "disk_kb": after / 1024,
            "reclaimed_kb": (before - after) / 1024,
        })

    unbounded_kb = sum(len(str(_record(i))) for i in range(written)) / 1024

    L = []
    add = L.append
    add("# SE-3 — shipping the WAL, and reclaiming the disk")
    add("")
    add("Generated by `run_shipping.py`. `run_wal.py` ends by saying the WAL")
    add("*bounds the loss to what has not yet shipped* and *does not replace")
    add("shipping*. Both were promises about code that did not exist —")
    add("`DurableAuditLog.drain()` moved records between two Python lists, and")
    add("nothing ever deleted anything, so the log grew forever and \"shipped\"")
    add("meant nothing a crash would respect.")
    add("")

    add("## The run")
    add("")
    add("{:,} decisions across {} cycles. The sink is **down for cycles {}**".format(
        written, CYCLES, "-".join(str(c) for c in sorted(down))))
    add("and permanently rejects one record (`{}`) throughout.".format(poison_id))
    add("")
    add("| cycle | sink | written | shipped | unshipped | segments | deleted | disk KB | reclaimed KB |")
    add("|---|---|---|---|---|---|---|---|---|")
    for r in rows:
        add("| {} | {} | {:,} | {:,} | {:,} | {} | {} | {:,.1f} | {:,.1f} |".format(
            r["cycle"], r["sink"], r["written"], r["shipped"], r["unshipped"],
            r["segments"], r["deleted"], r["disk_kb"], r["reclaimed_kb"]))
    add("")

    add("## What the numbers say")
    add("")
    add("| | |")
    add("|---|---|")
    add("| decisions written | {:,} |".format(written))
    add("| reached the sink | {:,} |".format(len(sink.received)))
    add("| permanently rejected, routed to the poison list | {:,} |".format(
        shipper.stats.poisoned))
    add("| segments deleted | {:,} |".format(shipper.stats.segments_deleted))
    add("| disk reclaimed | {:,.1f} KB |".format(
        shipper.stats.bytes_reclaimed / 1024))
    add("| peak disk held | {:,.1f} KB |".format(peak_disk / 1024))
    add("| disk if nothing were ever truncated | ~{:,.1f} KB |".format(unbounded_kb))
    add("| final disk | {:,.1f} KB |".format(_disk(wal) / 1024))
    add("| retries against the failing sink | {:,} |".format(shipper.stats.retries))
    add("")
    add("**{:,} + {:,} = {:,}** — every decision either reached the sink or was".format(
        len(sink.received), shipper.stats.poisoned,
        len(sink.received) + shipper.stats.poisoned))
    add("routed as poison. None was dropped.")
    add("")
    add("Watch the disk column through cycles {}. The sink is down, nothing".format(
        "-".join(str(c) for c in sorted(down))))
    add("ships, nothing is deleted, and the log grows — **an unavailable sink")
    add("costs disk, not data**, which is the entire point of a write-ahead log.")
    add("When the sink returns, the backlog ships and the space comes back.")
    add("")

    add("## Why truncation is a delete and not a rewrite")
    add("")
    add("The obvious implementation — read the records, drop the shipped ones,")
    add("write the rest back — has a window where the old file is gone and the")
    add("new one is incomplete. Crash there and you have lost **every** record,")
    add("including the unshipped ones the exercise was supposed to protect.")
    add("Rewriting an append-only log to make it shorter converts a durable")
    add("store into a lossy one at exactly the moment it is most full.")
    add("")
    add("So the log is segmented. Truncation deletes whole segments in which")
    add("every record is acknowledged. A delete is atomic in a way a rewrite is")
    add("not: the segment is either there or it is not, and the segments around")
    add("it are untouched either way. The **active** segment is never deleted —")
    add("it is still being appended to, and removing it would take records")
    add("written after the watermark was computed.")
    add("")

    add("## The ordering, which is the whole correctness argument")
    add("")
    add("| order | crash in between costs |")
    add("|---|---|")
    add("| **watermark first, delete second** | segments the watermark says are shipped stay on disk. The next pass re-ships them and the sink dedupes. **Cost: a duplicate delivery.** |")
    add("| delete first, watermark second | records deleted with nothing recording they were ever shipped. **Cost: a decision the firm made about a customer's money, with no trace.** |")
    add("")
    add("`tests/test_shipping.py` executes the wrong order and measures the")
    add("loss, rather than asserting the right one works — because an ordering")
    add("rule that is only a comment gets simplified away later by someone who")
    add("finds it arbitrary.")
    add("")
    add("At-least-once with a durable watermark is the correct trade, and it is")
    add("**only** correct because the sink is idempotent on `decision_id`. That")
    add("is a constraint on the sink, invisible from the sink's side, so it is")
    add("asserted from the shipper's tests. A shipper built on a non-idempotent")
    add("sink cannot use this ordering and has no safe alternative.")
    add("")

    add("## The poison record")
    add("")
    add("One record the sink will never accept. Retrying it forever blocks the")
    add("watermark, the WAL never truncates, and the disk fills up because of a")
    add("single malformed row — a availability incident caused by one bad")
    add("record.")
    add("")
    add("So a permanent rejection is distinguished from a transient failure. On")
    add("a permanent one the batch is retried **record by record** to find the")
    add("poison rather than condemning its ninety-nine innocent neighbours, and")
    add("the offender is marked acknowledged so it stops blocking — which is")
    add("only acceptable because it is handed to the caller in `shipper.poison`.")
    add("Dropping it silently would be the actual bug.")
    add("")

    add("## What this still does not do")
    add("")
    add("- **The sink is in-process.** A real one is a network service, and")
    add("  every interesting failure it has — partial batch acceptance, a slow")
    add("  response that later succeeds, an ack lost on the return path — is a")
    add("  network failure this cannot produce. The retry logic here is")
    add("  structured for those and tested against none of them.")
    add("- **The watermark is a set of ids, not an offset.** That is honest at")
    add("  this scale and does not survive volume: the file grows with every")
    add("  decision ever shipped. A production watermark is a per-segment high")
    add("  water mark, so it stays constant-sized. Changing it is not hard and")
    add("  is not done, because pretending the current one scales would be the")
    add("  claim worth avoiding.")
    add("- **No compaction.** Segments are deleted whole or kept whole. A")
    add("  segment holding one unshipped record among thousands stays entirely.")
    add("- **Single disk.** A disk that dies takes the unshipped tail with it.")
    add("  The WAL bounds that loss to the shipping interval and does not")
    add("  eliminate it.")

    doc = "\n".join(L)
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "docs" / "SHIPPING.md").write_text(doc, encoding="utf-8")
    print(doc)
    print()
    print("wrote docs/SHIPPING.md")

    # A failure here is a failure of the run, not a note in a document.
    accounted = len(sink.received) + shipper.stats.poisoned
    if accounted != written:
        print("\n{} of {} decisions are unaccounted for.".format(
            written - accounted, written))
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
