"""Velocity counters on Redis, with the atomicity done properly.

`velocity.py` proves the semantics with a mutex in one process. That is not what
production looks like: the counter lives in Redis, several gateway instances hit
the same key, and a process-local lock protects nothing at all across them.

The naive Redis version has exactly the same bug as the naive in-process one:

    n = redis.zcard(key)          # read
    redis.zadd(key, {member: ts}) # modify-write
    -> two round trips, and another instance interleaves between them

The fix is not a distributed lock (a round trip to acquire, a round trip to
release, and a correctness argument about what happens when the holder dies).
It is to make the whole read-trim-write-count sequence ONE operation. Redis runs
Lua scripts atomically: nothing else executes on that key while the script runs.

The script below does four things in one atomic step:
  1. trim the sliding window (ZREMRANGEBYSCORE)
  2. add this event (ZADD)
  3. count what remains (ZCARD)
  4. set a TTL so an idle key does not leak memory forever

Sorted sets rather than counters because the window has to SLIDE. A plain INCR
with EXPIRE gives a fixed bucket, and a fixed 60s bucket lets an attacker put 10
transactions at 11:59:59 and 10 at 12:00:01 without ever tripping a "20 per
minute" rule.

fakeredis is used in tests. It executes the same Lua, so the atomicity argument
is exercised rather than asserted -- but it is a single process, so it cannot
prove behaviour across a real cluster. That limitation is stated in the README
rather than glossed.
"""
from __future__ import annotations

import itertools

# KEYS[1] = velocity key
# ARGV[1] = now (ms), ARGV[2] = window (ms), ARGV[3] = unique member id
SLIDING_WINDOW_LUA = """
local now    = tonumber(ARGV[1])
local window = tonumber(ARGV[2])
local member = ARGV[3]

redis.call('ZREMRANGEBYSCORE', KEYS[1], '-inf', now - window)
redis.call('ZADD', KEYS[1], now, member)
local count = redis.call('ZCARD', KEYS[1])
redis.call('PEXPIRE', KEYS[1], window)
return count
"""

# Read-only variant: counts without recording. Used by rules that must not
# themselves inflate the counter they are testing.
COUNT_ONLY_LUA = """
local now    = tonumber(ARGV[1])
local window = tonumber(ARGV[2])
redis.call('ZREMRANGEBYSCORE', KEYS[1], '-inf', now - window)
return redis.call('ZCARD', KEYS[1])
"""


class RedisVelocity:
    """Sliding-window velocity counter backed by Redis."""

    class Unavailable(Exception):
        pass

    def __init__(self, client, window_ms: int = 60_000, namespace: str = "vel"):
        self.client = client
        self.window_ms = window_ms
        self.namespace = namespace
        self.available = True
        self._incr = client.register_script(SLIDING_WINDOW_LUA)
        self._count = client.register_script(COUNT_ONLY_LUA)
        # itertools.count(), not `self._seq += 1`. See incr_and_count for why
        # that distinction cost 24% of the increments on a real server.
        self._seq = itertools.count(1)

    def _key(self, key: str) -> str:
        return "{}:{}".format(self.namespace, key)

    def incr_and_count(self, key: str, now_ms: int) -> int:
        if not self.available:
            raise RedisVelocity.Unavailable("velocity store is down")
        # The member must be unique per event, or two events at the same
        # millisecond collapse into one sorted-set entry and the counter
        # undercounts exactly when traffic is densest.
        #
        # This read `self._seq += 1`, which is a read-modify-write on a plain
        # Python int and is NOT atomic across threads -- the bytecode is a LOAD,
        # an ADD and a STORE, and the interpreter can switch between any two of
        # them. Two threads then build the SAME member string, ZADD overwrites
        # instead of adding, and the count is silently low.
        #
        # Measured on a real server, 50 threads x 200 increments: 7,600 of
        # 10,000. The Lua was atomic the whole time. The uniqueness the whole
        # scheme depends on was generated by racy client code OUTSIDE it, which
        # is a good reminder that "the critical section is atomic" is a claim
        # about the critical section and not about the call site.
        #
        # `next()` on an itertools.count is a single C call and cannot be
        # interrupted partway. A lock would also work and costs more.
        member = "{}-{}".format(now_ms, next(self._seq))
        try:
            return int(self._incr(keys=[self._key(key)],
                                  args=[now_ms, self.window_ms, member]))
        except Exception as exc:
            raise RedisVelocity.Unavailable(str(exc)) from exc

    def count(self, key: str, now_ms: int) -> int:
        if not self.available:
            raise RedisVelocity.Unavailable("velocity store is down")
        return int(self._count(keys=[self._key(key)],
                               args=[now_ms, self.window_ms]))


class NaiveRedisVelocity:
    """Deliberately racy: read, then modify-write, in two round trips.

    Kept so the exactness test has something to fail against. A concurrency test
    that has never produced a wrong answer is not evidence of anything.
    """

    def __init__(self, client, window_ms: int = 60_000, namespace: str = "naive",
                 on_race=None):
        self.client = client
        self.window_ms = window_ms
        self.namespace = namespace
        self._seq = 0
        # Called in the read->write gap. None in production (this class exists
        # only for the negative-control test); the test injects a barrier so
        # every worker reads before any writes -- making the lost update
        # deterministic instead of dependent on the runner's thread scheduling.
        self.on_race = on_race

    def incr_and_count(self, key: str, now_ms: int) -> int:
        k = "{}:{}".format(self.namespace, key)
        self.client.zremrangebyscore(k, "-inf", now_ms - self.window_ms)
        current = self.client.zcard(k)              # READ
        self._seq += 1
        if self.on_race is not None:
            self.on_race()                          # force the interleave here
        self.client.zadd(k, {"{}-{}".format(now_ms, self._seq): now_ms})
        return current + 1                          # stale read + 1


def connect(url: str | None = None, fake: bool = False,
            pool_size: int = 64, socket_timeout: float = 1.0,
            retries: int = 0):
    """Real Redis when a URL is given, fakeredis otherwise.

    fakeredis executes the same Lua, so the script's atomicity is genuinely
    exercised. What it cannot exercise is cross-node behaviour, failover, or
    network partitions -- for those the answer is a real cluster, and this repo
    does not have one.
    """
    if fake or url is None:
        import fakeredis
        return fakeredis.FakeStrictRedis(decode_responses=True)
    import redis

    # TWO SETTINGS THAT ARE NOT DEFAULTS AND SHOULD BE.
    #
    # max_connections: the default pool is unbounded in name and serialised in
    # practice -- 50 threads sharing it produced a p99 of 142ms against a 20ms
    # velocity budget while p50 stayed at 17.7ms. That tail was almost entirely
    # time spent waiting for a connection, not time spent in Redis. A pool
    # sized to the worker count is the difference between measuring the
    # dependency and measuring the queue in front of it.
    #
    # socket_timeout: the library default lets a call to a dead server hang for
    # SECONDS -- measured against a dead port, ~2,000ms, which is 100x the whole
    # stage budget. Failing must not take longer than succeeding.
    #
    # The first attempt set this to 0.015s, "inside the 20ms allocation", and it
    # timed out HEALTHY calls -- because the measured p50 against this Redis is
    # 17.7ms, so a 15ms timeout is below the dependency's own median. A timeout
    # must sit above the healthy p99, not below the budget; setting it from the
    # budget instead of from the measurement turns every slow-but-fine request
    # into an outage.
    #
    # 0.25s was the second attempt and it was also wrong: at 50 threads the
    # measured MAX is ~1,800ms, so a quarter-second timeout discarded most of
    # the tail and the counter came back 88 of 10,000.
    #
    # 1.0s is set from the measured distribution rather than from the budget.
    # It is still half the ~2,000ms the library default takes to fail, so the
    # dead-server path is faster than it was, and it is nowhere near 20ms.
    #
    # The conclusion that actually matters, and it is uncomfortable: at a p50 of
    # ~18ms and a max near 1.8s over this transport, Redis DOES NOT FIT a 20ms
    # velocity budget. The budget was written against an in-process counter.
    # Adopting Redis means either rewriting the budget or co-locating Redis so
    # the hop is a loopback rather than a cross-VM one -- and SE-3's README says
    # that rather than quietly keeping the old number.
    #
    # ------------------------------------------------------------------
    # CO-LOCATION WAS THE OPEN QUESTION AND IT IS NOW MEASURED.
    #
    # Every number above was taken from Windows across the WSL boundary. Run
    # from a process ON THE SAME HOST as Redis, the same Lua script measures:
    #
    #     p50 0.33ms   p90 0.62ms   p99 4.95ms   p999 12.04ms   max 15.30ms
    #
    # A 54x improvement at the median, and the whole distribution including the
    # p999 fits inside the 20ms allocation. So the answer to the question this
    # comment posed is: co-locating Redis makes it fit, and the budget does not
    # need rewriting for the HEALTHY path.
    #
    # A second measurement from the same run, which refutes a hypothesis rather
    # than confirming one: latency does NOT track window size. A key holding
    # 5,400 members measures p50 0.31ms against 0.28ms for one holding 410. The
    # expectation was that a velocity window under attack -- which is exactly
    # when the set is largest -- would be slower to evaluate. At these sizes
    # ZREMRANGEBYSCORE, ZADD and ZCARD are all dominated by scheduler noise, and
    # the tail belongs to the round trip rather than to Redis's work. A bare
    # PING measures p99 6.31ms, HIGHER than the script's 4.95ms.
    # ------------------------------------------------------------------
    #
    # THE FAILURE PATH IS STILL BROKEN, AND NOT FOR THE REASON WRITTEN ABOVE.
    #
    # `retry_on_timeout=False` was set here in the belief that it stopped
    # retrying. It does not. redis-py 8.x separately defaults every connection
    # to `Retry(ExponentialWithJitterBackoff(), retries=10)` covering
    # ConnectionError, and that policy -- not the socket timeout -- is what
    # governs how long a dead server takes to fail. Measured against a closed
    # port:
    #
    #     socket_timeout=1.0s,   default retry  -> 3,234ms
    #     socket_timeout=0.015s, default retry  -> 4,061ms   (TIGHTER IS SLOWER)
    #     socket_timeout=1.0s,   retries=0      ->     0.4ms
    #     raw TCP connect, no redis at all      ->     0.5ms
    #
    # Tightening the timeout made failure SLOWER, because a shorter timeout lets
    # more of the ten retries complete inside the same wall clock while the
    # exponential backoff accumulates. And the timeout is irrelevant to a
    # refused connection in the first place: the RST arrives in half a
    # millisecond, so with retries off the client fails at the speed of TCP.
    #
    # SO THE TWO FAILURE MODES NEED TWO DIFFERENT CONTROLS, and conflating them
    # is what the earlier advice in run_redis_real.py did:
    #
    #   CONNECTION REFUSED   Redis is down. Bounded by the RETRY POLICY. The
    #                        socket timeout does nothing here.
    #   ACCEPTS BUT STALLS   Redis is up and wedged -- a long GC pause, a
    #                        saturated box, a network black hole. Bounded by
    #                        `socket_timeout`, and ONLY by it. Measured against a
    #                        socket that accepts and never replies: 1,003ms at
    #                        the 1.0s default, 16ms at a 15ms timeout. Exactly as
    #                        advertised, for this case and no other.
    #
    # `retries` is therefore set explicitly rather than left to the library.
    from redis.backoff import NoBackoff
    from redis.retry import Retry

    return redis.Redis.from_url(
        url,
        decode_responses=True,
        max_connections=pool_size,
        socket_timeout=socket_timeout,
        socket_connect_timeout=socket_timeout,
        # Zero retries at the CLIENT. A velocity check that is worth retrying is
        # worth retrying inside a deadline the caller owns, not inside a library
        # whose backoff schedule the caller cannot see. Ten retries with
        # exponential backoff behind a 20ms budget is a 3-second stall wearing a
        # 20ms label.
        retry=Retry(NoBackoff(), retries),
        retry_on_timeout=False)
